name: Micah Miller-Eshleman
description: Blog & Projects
meta_description: "Your New Jekyll Site, Blogging about stuffs"

aboutPage: true

markdown: kramdown
highlighter: rouge

paginate: 20
baseurl: 'https://pranksinatra.github.io/'
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Prose.io Configuration
prose: 
    media: 'assets/images'

# Details for the RSS feed generator
url:            'http://micahjon.com'
author:         'Micah Miller-Eshleman'
authorTwitter:  'YourTwitterUsername'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
