---
title: Pranksinatra.Github.Io
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: drafts
  values:
    layout: post
name: Micah Miller-Eshleman
description: Blog & Projects
enable_disqus: true
highlighter: rouge
paginate: 20
baseurl: "/"
domain_name: http://micahjon.com
google_tag_manager: GTM-MZB37F
prose:
  media: assets/images
url: http://micahjon.com
author: Micah Miller-Eshleman
authorTwitter: YourTwitterUsername
permalink: "/:year/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded
plugins:
- jekyll-redirect-from
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
