---
title: Pranksinatra.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: drafts
  values:
    layout: post
name: Micah Miller-Eshleman
description: Blog & Projects
meta_description: Your New Jekyll Site, Blogging about stuffs
aboutPage: true
markdown: kramdown
highlighter: rouge
paginate: 20
baseurl: https://pranksinatra.github.io/
domain_name: http://yourblog-domain.com
google_analytics: UA-XXXXXXXX-X
disqus: false
disqus_shortname: your-disqus-shortname
prose:
  media: assets/images
url: http://micahjon.com
author: Micah Miller-Eshleman
authorTwitter: YourTwitterUsername
permalink: "/:year/:title/"
